<div class="form-group row">
	       {{Form::label('subject', 'Subject', ['class'=>'col-sm-2 col-form-label'])}} 
		   <div class="col-sm-10">
		    	{{Form::select(
		    		'subject',		    		
		    		['Mathematics' => 'Mathematics',
		    		 'Accounting' => 'Accounting',
		    		 'Anthropology'=>'Anthropology',
		    		 'Art and Architecture'=>'Art and Architecture',
		    		 'Astronomy'=>'Astronomy',
		    		 'Biology'=>'Biology',
		    		 'Business'=>'Business',
		    		 'Chemistry'=>'Chemistry',
		    		 'Classic English Literature'=>'Classic English Literature',
		    		 'Communication'=>'Communication',
		    		 'Computer Science'=>'Computer Science', 
		    		 'Criminal Law'=>'Criminal Law',
		    		 'Culture'=>'Culture',
		    		 'Economics'=>'Economics',
		    		 'Ecology'=>'Ecology',
		    		 'Education'=>'Education',
		    		 'Engineering'=>'Engineering',
		    		 'English'=>'English',
		    		 'Environmental Studies'=>'Environmental Studies',
		    		 'Family and Consumer Science'=>'Family and Consumer Science',
		    		 'Film Studies'=>'Film Studies',
		    		 'Finance'=>'Finance',
		    		 'Geology'=>'Geology',
		    		 'Geography'=>'Geography',
		    		 'History'=>'History',
		    		 'Human Resource Management'=>'Human Resource Management',
		    		 'Investments'=>'Investments',
		    		 'Journalism'=>'Journalism',
		    		 'Law'=>'Law',
		    		 'Literature'=>'Literature',
		    		 'Management'=>'Management',
		    		 'Marketing'=>'Marketing',
		    		 'Mathematics'=>'Mathematics',
		    		 'Medicine'=>'Medicine',
		    		 'Music'=>'Music',
		    		 'Nursing'=>'Nursing',
		    		 'Philosophy'=>'Philosophy',
		    		 'Physics'=>'Physics',
		    		 'Political Science'=>'Political Science',
		    		 'Poetry'=>'Poetry',
		    		 'Psychology'=>'Psychology',
		    		 'Religious Studies'=>'Religious Studies',
		    		 'Shakespeare Studies'=>'Shakespeare Studies',
		    		 'Statistics' => 'Statistics',
		    		 'Sociology'=>'Sociology',
		    		 'Sports'=>'Sports',
		    		 'Technology'=>'Technology',
		    		 'Theater Studies'=>'Theater Studies',
		    		 'Women and Gender Studies'=>'Women and Gender Studies',
		    		 'World Affairs'=>'World Affairs',
		    		 'World Literature'=>'World Literature',
		    		 'Other'=>'Other'		    		    		 		    		 
		    		], 
		    		 'Accounting',
		    		 ['class'=>'form-control']
		    	)}}	      		
		    </div>
		</div>